site_name: Sparrow SMS
site_url: http://api.sparrowsms.com
repo_url: http://github.com/sparrowsms/apidocs
site_description: Sparrow SMS Official Developers API.
site_author: Sparrow SMS (@sparrowsms)
theme: 'readthedocs'
nav:
  - Home: 'index.md'
  - Documentation: 'documentation.md'
  - Push SMS (MT): 'outgoing_sendsms.md'
  - Credits: 'outgoing_credits.md'
  - Pull SMS (MO): 'incoming.md'
  - Examples: 'examples.md'
  - Push SMS (MT) Examples: 'examples_outgoing.md'
  - Credits Examples: 'examples_credits.md'
  - Pull SMS (MO) Examples: 'examples_incoming.md'
